#!/usr/bin/env bash
#
# Regenerate the frontend's server-side AWS config from Terraform state.
#
# Next.js only reads .env files from its own project root, so the repo-root
# .env.local is invisible to the app. This writes the resource names Terraform
# actually created into the one file Next.js will read, which keeps the two
# from drifting apart by hand.
#
# Credentials are deliberately NOT written here. The AWS SDK falls back to its
# default provider chain (~/.aws/credentials), so refreshing the sandbox login
# in one place is enough for both the CLI and the app.
#
# Usage:  bash iac/sync-env.sh
# Reads local state only — no AWS calls, so it works with expired credentials.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
iac_dir="$repo_root/iac"
env_file="$repo_root/frontend/meong-my-way/.env.local"

read_output() {
  terraform -chdir="$iac_dir" output -raw "$1" 2>/dev/null || echo ""
}

bucket="$(read_output s3_bucket_name)"
resumes_table="$(read_output dynamodb_resumes_table_name)"
region="$(grep -E '^\s*default\s*=' "$iac_dir/variables.tf" | sed -n '1s/.*"\(.*\)".*/\1/p')"
region="${region:-us-east-1}"

missing=0
if [ -z "$bucket" ]; then
  echo "WARN: no s3_bucket_name output — run 'terraform -chdir=iac apply' first." >&2
  missing=1
fi
if [ -z "$resumes_table" ]; then
  echo "WARN: no dynamodb_resumes_table_name output — the resumes table has not" >&2
  echo "      been applied yet. Run 'terraform -chdir=iac apply'." >&2
  missing=1
fi

cat > "$env_file" <<EOF
# GENERATED by iac/sync-env.sh — do not edit by hand.
# Re-run that script after any 'terraform apply' that changes resource names.
#
# Server-only. Never add a NEXT_PUBLIC_ prefix to anything in this file:
# NEXT_PUBLIC_ values are inlined into the browser bundle.

AWS_REGION=$region
S3_BUCKET_NAME=$bucket
DYNAMODB_RESUMES_TABLE=$resumes_table

# Credentials intentionally omitted. The SDK reads ~/.aws/credentials via its
# default provider chain, so the sandbox login is refreshed in exactly one
# place. Setting AWS_ACCESS_KEY_ID here would override that and go stale.
EOF

echo "Wrote $env_file"
echo "  AWS_REGION             = $region"
echo "  S3_BUCKET_NAME         = ${bucket:-<empty>}"
echo "  DYNAMODB_RESUMES_TABLE = ${resumes_table:-<empty>}"

exit "$missing"
